import positions from "./util";
const database = [
  {
    firstname: "Katelyn",
    lastname: "McPherson",
    position: "manager",
    email: "katelyn@gmail.com",
    password: "passwordone",
    earnings: positions.manager.earnings,
    deduction: positions.manager.deduction,
  },
  {
    firstname: "Harvey",
    lastname: "Foster",
    position: "marketer",
    email: "harvey@gmail.com",
    password: "passwordtwo",
    earnings: positions.marketer.earnings,
    deduction: positions.marketer.deduction,
  },
  {
    firstname: "Nicole",
    lastname: "Whitney",
    position: "cashier",
    email: "nicole@gmail.com",
    password: "passwordthree",
    earnings: positions.cashier.earnings,
    deduction: positions.cashier.deduction,
  },
  {
    firstname: "Jeffery",
    lastname: "Cantu",
    position: "cleaner",
    email: "jeffery@gmail.com",
    password: "passwordfour",
    earnings: positions.cleaner.earnings,
    deduction: positions.cleaner.deduction,
  },
  {
    firstname: "Galilea",
    lastname: "Duarte",
    position: "manager",
    email: "galilea@gmail.com",
    password: "passwordfive",
    earnings: positions.manager.earnings,
    deduction: positions.manager.deduction,
  },
  {
    firstname: "Abdullah",
    lastname: "Truong",
    position: "marketer",
    email: "truong@gmail.com",
    password: "passwordsix",
    earnings: positions.marketer.earnings,
    deduction: positions.marketer.deduction,
  },
  {
    firstname: "Judith",
    lastname: "Adkins",
    position: "cashier",
    email: "adkins@gmail.com",
    password: "passwordseven",
    earnings: positions.cashier.earnings,
    deduction: positions.cashier.deduction,
  },

  {
    firstname: "Kylo",
    lastname: "Browning",
    position: "cleaner",
    email: "browning@gmail.com",
    password: "passwordeight",
    earnings: positions.cleaner.earnings,
    deduction: positions.cleaner.deduction,
  },
  {
    firstname: "Princess",
    lastname: "Lucas",
    position: "manager",
    email: "lucas@gmail.com",
    password: "passwordnine",
    earnings: positions.manager.earnings,
    deduction: positions.manager.deduction,
  },

  {
    firstname: "Chance",
    lastname: "Mueller",
    position: "marketer",
    email: "mueller@gmail.com",
    password: "passwordten",
    earnings: positions.marketer.earnings,
    deduction: positions.marketer.deduction,
  },

  {
    firstname: "Imani",
    lastname: "Huang",
    position: "cashier",
    email: "huang@gmail.com",
    password: "passwordeleven",
    earnings: positions.cashier.earnings,
    deduction: positions.cashier.deduction,
  },

  {
    firstname: "Ayaan",
    lastname: "Weber",
    position: "cleaner",
    email: "weber@gmail.com",
    password: "passwordtwelve",
    earnings: positions.cleaner.earnings,
    deduction: positions.cleaner.deduction,
  },

  {
    firstname: "Alayah",
    lastname: "Gillespie",
    position: "manager",
    email: "gillespie@gmail.com",
    password: "passwordthirteen",
    earnings: positions.manager.earnings,
    deduction: positions.manager.deduction,
  },

  {
    firstname: "Forest",
    lastname: "Bauer",
    position: "marketer",
    email: "bauer@gmail.com",
    password: "passwordfourteen",
    earnings: positions.marketer.earnings,
    deduction: positions.marketer.deduction,
  },

  {
    firstname: "Haley",
    lastname: "Lozano",
    position: "cashier",
    email: "lozano@gmail.com",
    password: "passwordfifteen",
    earnings: positions.cashier.earnings,
    deduction: positions.cashier.deduction,
  },

  {
    firstname: "Boone",
    lastname: "Good",
    position: "cleaner",
    email: "good@gmail.com",
    password: "passwordsixteen",
    earnings: positions.cleaner.earnings,
    deduction: positions.cleaner.deduction,
  },

  {
    firstname: "Nathalia",
    lastname: "Bush",
    position: "manager",
    email: "bush@gmail.com",
    password: "passwordseventeen",
    earnings: positions.manager.earnings,
    deduction: positions.manager.deduction,
  },

  {
    firstname: "Gunnar",
    lastname: "Moyer",
    position: "marketer",
    email: "moyer@gmail.com",
    password: "passwordeighteeen",
    earnings: positions.marketer.earnings,
    deduction: positions.marketer.deduction,
  },
  {
    firstname: "Zola",
    lastname: "Ortiz",
    position: "cashier",
    email: "Ortiz@gmail.com",
    password: "passwordninteen",
    earnings: positions.cashier.earnings,
    deduction: positions.cashier.deduction,
  },
  {
    firstname: "Landon",
    lastname: "Goodwin",
    position: "cleaner",
    email: "aoodwin@gmail.com",
    password: "passwordtewnty",
    earnings: positions.cleaner.earnings,
    deduction: positions.cleaner.deduction,
  },
];

export default database;
